### ISSUE TITLE
Importing actions

### ISSUE THREAD

**Issue by impredicative** [fboender/jsonxs#1]
Thanks for this promising package. Can the actions be made available in `__init__.py` too? At this time I have to import them as `from jsonxs.jsonxs import ACTION_SET`, etc. and this pattern is a bit unusual.

**Comment by fboender** [comment]
Hi impredicative,

It looks like you're right. That's pretty stupid of me. I'm probably one of the few people actually using this lib, and I use the string versions in some of my programs, so I never ran into this problem.

I've committed a fix to the master branch. I'll release it on pip in a few hours. In the meantime, you can use the master branch if you'd like to.

Thanks for reporting the problem. I'll update this bug report when the fix is available on PyPi.

**Comment by impredicative** [comment]
Master branch looks good. Thanks. I suspect that changes might get shown practically immediately at https://pypi.org/project/jsonxs/ but less quickly at https://pypi.python.org/pypi/jsonxs/

**Comment by fboender** [comment]
Version 0.5 has been uploaded to the Python package index. You can install or upgrade it with pip. Note that the import syntax for the package has changed. You should now use:

    import jsonxs
    
    data = {'foo': 1}
    jsonxs.jsonxs(data, 'bar', jsonxs.ACTION_SET, 2)

Or optionally:

    from jsonxs import *
    jsonxs(data, 'bar', ACTION_SET, 2)

But this is not recommended as it polutes the main space.

**Comment by impredicative** [comment]
0.5 works well. I now use the recommended syntax.
